name: 'Simple Action'
description: 'A very simple GitHub action implementing the command design pattern'
inputs:
  command:
    description: 'Command to run'
    required: true

  issue-number:
    description: 'Issue Number'
    required: true

  token:
    description: 'Access token'
    required: true

  org:
    description: 'Repository Owner (User or Organization)'
    required: false

  repo:
    description: 'Repository name'
    required: false

outputs:
  result:
    description: 'Result of the command executed'

runs:
  using: 'node12'
  main: 'dist/index.js'

# Add more steps, for example, you could also specify a pre-action script to be run:
# pre-actions:
#   - name: 'Set up Node.js'
#     uses: actions/setup-node@v2
#     with:
#       node-version: '12'

# You can also add any other commands as part of the action if needed.